application: follerme
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: templates/static
  
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /robots.txt
  static_files: templates/static/robots.txt
  upload: templates/static/robots.txt
  
- url: /favicon.ico
  static_files: templates/static/images/favicon.ico
  upload: templates/static/images/favicon.ico

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on

error_handlers:
  - file: templates/default_error.html
  - error_code: over_quota
    file: templates/error_over_quota.html
